//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnProducts.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProduct()
        {
            this.tProductImage = new HashSet<tProductImage>();
            this.tEfficacy = new HashSet<tEfficacy>();
        }
    
        public int fProductID { get; set; }
        public string fProductChName { get; set; }
        public string fProductDesc { get; set; }
        public Nullable<int> fUnitPrice { get; set; }
        public string fQuantityPerUnit { get; set; }
        public Nullable<int> fUnitsInStock { get; set; }
        public Nullable<bool> fDiscontinued { get; set; }
        public int fCategoryID { get; set; }
    
        public virtual tCategory tCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProductImage> tProductImage { get; set; }
        public virtual tProductUnilateral tProductUnilateral { get; set; }
        public virtual tProductVegetableoil tProductVegetableoil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEfficacy> tEfficacy { get; set; }
    }
}
